a: Extendify Plugin
e: Airtable DB

extendifyServer: {
  label: Extendify Server

  dashboardServer: {
    label: dashboard.extendiy.com
    ls: Laravel Server
    cl: Cache Layer

    ls -> cl
  }

  apiServer:  {
    label: api.extendiy.com/api/templates
    nj: Next.js Server

    _.dashboardServer.ls -> nj: 2 see that
  }

  dashboardServer -> apiServer
  dashboardServer.ls -> apiServer.nj: 3 Custom connector label
}

a -> extendifyServer: API request
x -> y: hello world
x -> z: hello again
