a: Extendify Plugin
e: Airtable DB

extendifyServer: Extendify Server {
  dashboardServer: dashboard.extendiy.com {
    ls: Laravel Server
    cl: Cache Layer

    ls -> cl
  }

  apiServer: api.extendiy.com/api/templates {
    nj: Next.js Server
    _ls -> nj
  }

  dashboardServer -> apiServer
}

a -> extendifyServer: API request
x -> y: hello world
x -> z: hello again
