name: D2 CI

on:
  # push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install D2
        run: |
          sudo curl -fsSL https://d2lang.com/install.sh | sudo sh -s --
          #d2 --help
          #man d2
          d2 file.d2
          ls
