name: D2 CI

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install D2
        run: sudo curl -fsSL https://d2lang.com/install.sh | sudo sh -s --

      - name: Compile D2 files
        run: |
          d2 --help
          man d2
          d2 d2/file.d2 d2/svg/file.svg
          ls

      - name: List compiled D2 files
        run: |
          git status
          git ls-files --others --exclude-standard

      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ secrets.GITHUB_REF_NAME }}
          force: true
          message: 'Pushed new files'
