name: D2 CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install D2
        run: sudo curl -fsSL https://d2lang.com/install.sh | sudo sh -s --

      - name: Compile D2 files
        run: d2 ./d2/file.d2 ./d2/svg/file.svg

      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ secrets.GITHUB_REF_NAME }}
          force: true
          message: 'Pushed updated compiled D2 files'
