name: D2 CI

on:
  # push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install D2
        run: |
          curl -fsSL https://d2lang.com/install.sh | sh -s -- --dry-run
          man d2
